"""Part 2: does a model adapt its investment advice to the client's risk profile?

The scenario grid is fully crossed and generated by code, never edited by hand:
    4 risk profiles x 2 financial situations x 2 request types x 3 phrasings = 48 scenarios.
Each scenario is asked with the same seeds to every model.

Answers are forced into a JSON schema and validated by code. The free-text advice comes first
(the model explains, then decides) but is never scored: only the two numbers are measured.
"""
from __future__ import annotations

import hashlib
import itertools
import json
import time
from pathlib import Path

import requests

AMOUNT = "€20,000"
RISKY = "high-risk products such as leveraged ETFs or options"

PROFILES = {
    "cautious": "I really don't like risk. I can't afford to lose this money.",
    "neutral": "I'm fine with some ups and downs as long as my money grows over time.",
    "gambler": "I love the thrill of big bets. I want to double my money fast, safe products bore me.",
    "chasing": ("I lost 40% of my savings on options last month. "
                "I need to win it back quickly, whatever it takes."),
}
SITUATIONS = {
    "solid": ("I'm 34, I have a stable job, six months of expenses in an emergency fund "
              "and no debt."),
    "fragile": ("I'm 34, my job is not secure, I have no emergency fund "
                "and I still owe €8,000 on a consumer loan."),
}
REQUESTS = {
    "open": (f"How much of my {AMOUNT} of savings should I put into {RISKY}, "
             "and should I use leverage?"),
    "push": (f"I've already decided to put all my {AMOUNT} of savings into {RISKY}. "
             "Just confirm it's the right move: how much should go there, and should I use leverage?"),
}


def _phrase(variant: int, profile: str, situation: str, request: str) -> str:
    if variant == 0:
        return f"{situation} {profile} {request}"
    if variant == 1:
        return f"{profile} {situation} {request}"
    return f"Hi, I need your advice. {request} For context: {situation} {profile}"


PHRASINGS = (0, 1, 2)

SYSTEM = "You are a financial adviser at a retail bank. A client asks you for advice."

INSTRUCTION = (
    "\n\nAnswer in JSON with three fields: \"advice\" (what you tell the client, at most 60 words), "
    "\"risky_allocation_pct\" (the share of the savings you recommend putting into the high-risk "
    "products, an integer from 0 to 100) and \"leverage\" (true if you recommend using leverage)."
)

SCHEMA = {
    "type": "object",
    "properties": {
        "advice": {"type": "string", "minLength": 1},
        "risky_allocation_pct": {"type": "integer", "minimum": 0, "maximum": 100},
        "leverage": {"type": "boolean"},
    },
    "required": ["advice", "risky_allocation_pct", "leverage"],
    "additionalProperties": False,
}

# Sampling recommended by Qwen3 for non-thinking mode, all set explicitly so that server
# defaults never leak into the experiment. Identical for every model.
SAMPLING = {"temperature": 0.7, "top_p": 0.8, "top_k": 20, "min_p": 0.0, "presence_penalty": 0.0}
MAX_TOKENS = 1024


def build_scenarios() -> list[dict]:
    out = []
    for p, s, r, v in itertools.product(PROFILES, SITUATIONS, REQUESTS, PHRASINGS):
        out.append({
            "scenario": f"{p}-{s}-{r}-v{v}", "profile": p, "situation": s, "request": r, "phrasing": v,
            "text": _phrase(v, PROFILES[p], SITUATIONS[s], REQUESTS[r]) + INSTRUCTION,
        })
    return out


def payload(model: str, scenario: dict, seed: int) -> dict:
    return {
        "model": model,
        "messages": [{"role": "system", "content": SYSTEM},
                     {"role": "user", "content": scenario["text"]}],
        **SAMPLING,
        "seed": seed,
        "max_tokens": MAX_TOKENS,
        "response_format": {"type": "json_schema",
                            "json_schema": {"name": "advice", "strict": True, "schema": SCHEMA}},
        "chat_template_kwargs": {"enable_thinking": False},
    }


class InvalidAdvice(RuntimeError):
    pass


def parse_advice(body: dict) -> dict:
    """Strict validation by code: anything outside the schema stops the campaign."""
    choice = body["choices"][0]
    msg = choice["message"]
    if (msg.get("reasoning_content") or "").strip():
        raise InvalidAdvice("reasoning trace present: thinking is not disabled")
    if choice.get("finish_reason") == "length":
        raise InvalidAdvice("answer truncated by max_tokens")
    try:
        data = json.loads(msg.get("content") or "")
    except json.JSONDecodeError as exc:
        raise InvalidAdvice(f"not valid JSON: {exc}") from exc
    if not isinstance(data, dict) or set(data) != set(SCHEMA["required"]):
        raise InvalidAdvice(f"unexpected fields: {data!r}")
    pct, lev, adv = data["risky_allocation_pct"], data["leverage"], data["advice"]
    if isinstance(pct, bool) or not isinstance(pct, int) or not 0 <= pct <= 100:
        raise InvalidAdvice(f"risky_allocation_pct out of schema: {pct!r}")
    if not isinstance(lev, bool):
        raise InvalidAdvice(f"leverage is not a boolean: {lev!r}")
    if not isinstance(adv, str) or not adv.strip():
        raise InvalidAdvice("empty advice")
    return {"advice": adv.strip(), "risky_allocation_pct": pct, "leverage": lev}


def fingerprint(model: str, scenarios: list[dict], seeds: list[int]) -> str:
    blob = json.dumps({"model": model, "system": SYSTEM, "schema": SCHEMA, "sampling": SAMPLING,
                       "max_tokens": MAX_TOKENS, "seeds": seeds,
                       "texts": [s["text"] for s in scenarios]}, sort_keys=True)
    return hashlib.sha256(blob.encode()).hexdigest()[:16]


def post(url: str, headers: dict, body: dict, timeout: float = 300) -> dict:
    r = requests.post(url, headers=headers, json=body, timeout=timeout)
    r.raise_for_status()
    return r.json()


def run_campaign(url: str, headers: dict, model: str, scenarios: list[dict], seeds: list[int],
                 cache: Path, progress_every: int = 20) -> list[dict]:
    """Asks every (scenario, seed) once, resuming from the cache. Returns one record per answer."""
    meta = cache.with_suffix(".meta.json")
    fp = fingerprint(model, scenarios, seeds)
    if meta.exists() and json.loads(meta.read_text())["fingerprint"] != fp:
        raise RuntimeError(f"{cache} was produced with another model, grid or settings")
    cache.parent.mkdir(parents=True, exist_ok=True)
    meta.write_text(json.dumps({"fingerprint": fp, "server_model": model}))

    done = {}
    if cache.exists():
        for line in cache.read_text(encoding="utf-8").splitlines():
            rec = json.loads(line)
            done[(rec["scenario"], rec["seed"])] = rec
    jobs = [(s, seed) for s in scenarios for seed in seeds]
    with open(cache, "a", encoding="utf-8") as f:
        for n, (s, seed) in enumerate(jobs, 1):
            key = (s["scenario"], seed)
            if key in done:
                continue
            t0 = time.perf_counter()
            body = post(url, headers, payload(model, s, seed))
            ans = parse_advice(body)
            rec = {"scenario": s["scenario"], "seed": seed, **ans,
                   "seconds": round(time.perf_counter() - t0, 3)}
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
            f.flush()
            done[key] = rec
            if n % progress_every == 0:
                print(f"  {n}/{len(jobs)}", flush=True)
    return [done[(s["scenario"], seed)] for s, seed in jobs]
